set -g prefix C-a
unbind C-b
bind C-a send-prefix
set -g mouse on

# --- Panes ---
bind -N "Split pane horizontally" . split-window -h -c "#{pane_current_path}"
bind -N "Split pane vertically"   , split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Index + Shift hjkl
bind -r -N "Resize pane left"  H resize-pane -L 5
bind -r -N "Resize pane down"  J resize-pane -D 5
bind -r -N "Resize pane up"    K resize-pane -U 5
bind -r -N "Resize pane right" L resize-pane -R 5

# --- Navigation for vim-tmux-navigator ---
# (These are root bindings -n, so they don't usually appear in the prefix menu)
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'

tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

# --- Windows ---
bind -N "Switch to previous window" h previous-window
bind -N "Switch to next window"     l next-window

bind -N "Create new window"         m new-window -c "#{pane_current_path}"
bind -N "Kill current pane"         x kill-pane
bind -N "Kill current window"       z kill-window
bind -N "Toggle pane zoom"          f resize-pane -Z

# --- Plugins ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'alexwforsythe/tmux-which-key'

# DO NOT MOVE
run '~/.tmux/plugins/tpm/tpm'
